openapi: 3.0.0
info:
  title: Greetings
  description: Simple API to get greet a vistor
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Localhost for testing
paths:
  /greetings:
    get:
      summary: Returns a personalized greeting message
      description: This endpoint yields your personalized greeting message
      parameters: 
        - in: query
          name: name
          schema:
            type: string
          required: true
          description: Name to be displayed in greeting message
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: "Welcome: DiveIn"
        '400':
          description: Query parameter name missing
          content:
            text/plain:
              schema:
                type: string
                example: "Query parameter name missing"